version: '3'
services:
  nginx:
    container_name: nginx-container
    restart: always
    build: ./requirements/nginx/.
    image: nginx
  mariadb:
    container_name: mariadb-container
    restart: always
    build: ./requirements/mariadb/.
    image: mariadb
  wordpress:
    container_name: wordpress-container
    restart: always
    build: ./requirements/wordpress/.
    image: wordpress
