version: '3'
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:inception
    restart: on-failure
    env_file:
      - .env
    volumes:
      - 'db:/var/lib/mysql'
    networks:
      - docker-network
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:inception
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - 'wordpress:/var/www/html'
    ports:
      - '443:443'
    networks:
      - docker-network
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:inception
    restart: on-failure
    env_file:
      - .env
    volumes:
      - 'wordpress:/var/www/html'
    depends_on:
      - mariadb
    networks:
      - docker-network

# ----------------------- Bonus Part -----------------------

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    image: adminer:inception
    restart: on-failure
    depends_on:
      - mariadb
    ports:
      - '8080:8080'
    networks:
      - docker-network

  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    image: redis:inception
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - '6379:6379'
    networks:
      - docker-network

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/.
    image: ftp:inception
    restart: on-failure
    volumes:
      - 'wordpress:/var/www/html'
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "21:21"
    networks:
      - docker-network

  garage:
    container_name: garage
    build: ./requirements/bonus/website/.
    image: garage:inception
    restart: on-failure
    networks:
      - docker-network

  prometheus:
    container_name: prometheus
    build: ./requirements/bonus/grafana/prometheus/.
    image: prometheus:inception
    restart: on-failure
    ports:
      - '9090:9090'
    volumes:
      - 'prometheus_data:/prometheus'
    networks:
      - docker-network

  grafana:
    container_name: grafana
    build: ./requirements/bonus/grafana/.
    image: grafana:inception
    restart: on-failure
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - 'grafana:/var/lib/grafana'
    networks:
      - docker-network

# ----------------------------------------------------------

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/ykhadiri/data/db
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ykhadiri/data/wordpress
      o: bind
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ykhadiri/data/prometheus/prometheus_data
      o: bind
  grafana:
    driver: local
    driver_opts:
      type: none
      device: /home/ykhadiri/data/grafana
      o: bind

networks:
  docker-network:
    name: docker-network
    driver: bridge
