version: '3'
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    restart: on-failure
    image: mariadb
    env_file:
      - .env
    volumes:
      - 'db:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks:
      - docker-network
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    restart: on-failure
    image: nginx
    depends_on:
      - wordpress
    volumes:
      - 'wordpress:/var/www/html'
    ports:
      - '443:443'
    networks:
      - docker-network
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    restart: on-failure
    image: wordpress
    env_file:
      - .env
    volumes:
      - 'wordpress:/var/www/html'
    depends_on:
      - mariadb
    ports:
      - '9000:9000'
    networks:
      - docker-network

# ----------------------- Bonus Part -----------------------
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    image: adminer
    restart: always
    depends_on:
      - mariadb
    ports:
      - '8080:8080'
    networks:
      - docker-network

# ----------------------------------------------------------

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/ykhadiri/data/db
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ykhadiri/data/wordpress
      o: bind

networks:
  docker-network:
    name: docker-network
    driver: bridge
